server:
  port: 8083

  
  
# 数据源相关配置
spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.78.31.134:3306/dormitory_management?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 1qaz!QAZ
    type: com.alibaba.druid.pool.DruidDataSource
  servlet: 
    multipart: 
      max-file-size: 500KB
